### ISSUE TITLE
Could you post a non-minified version as well? 

### ISSUE THREAD

**Issue by Arlen22** [NoteSelf/NoteSelf.github.io#10]
Hi Daniello,
Could you post a version of the wiki that is not minified? Maybe at http://noteself.github.io/dev/? My only request is that it be exactly the same as the online one, except not minified, as the nightly does not seem to be the same as the online folder (I wouldn't expect it to, given the name). This would make it a lot easier for me to inspect the code when I notice problems (and post new feature ideas).
Thanks

**Comment by danielo515** [comment]
Hello @Arlen22

There is a similar issue. Seen that more people is gaining intereste on Noteself, and what is more important , interest to collaborate , I'm planning to deploy all the code that empowers Noteself to the current repository. 
The reason why it is not available already it's because I have to tiddy the build process a bit, so other people can use on their computers .

Hope this weekend I can find time .

Regards , and thanks for your interest

**Comment by danielo515** [comment]
In any case, most of the code is on tiddlypouch repository, which is available already. Regards

**Comment by Arlen22** [comment]
This is true, but it requires me knowing which version is the one online
and then loading that into a tiddly wiki and running it on my current
database. Last time I tried that I seemed to run into problems :)

**Comment by danielo515** [comment]
You're right.
Expect one unminified version this night or tomorrow

**Comment by danielo515** [comment]
Dear Arlen,

I just uploaded the code that powers NoteSelf to the develop branch.
I also added a travis-ci file that builds the website:
 - index page (presentation)
 - online version
 - development version. This one has the unminified code

So, in order to use te version without the minified code you have to go to [noteself/dev](https://noteself.github.io/dev)

Now you can play with it as long as you want!!!
