### ISSUE TITLE
Any suggestion to add Noteself as a TW5 plugin?

### ISSUE THREAD

**Issue by mauloop** [NoteSelf/NoteSelf.github.io#26]
Is there a way to add Noteself to existing TW5 wikis as a plugin. I tried with a 5.1.13 version, installed the plugin and manually the stuff in the head section of the file. What else to make it to work?

It would be more comfortable for me to add the plugin to existing wikis, than export/import lot of tiddlers to the freshly downloaded noteself file.

P.S.: great work! I appreciate Noteself features very much.

**Comment by danielo515** [comment]
Hello mauloop,

First let me clarify that NoteSelf is not a plugin, it is a tiddlywiki edition. It may be sound irrelevant but it is a very important distinction. NoteSelf is amied at beign a product for the most of users, and to provide an user friendly and smooth experience. This is because I don't have time to give support to all the users that wants to try themselves. 

Also, installing the required plugins on a standalone tiddlywiki makes little sense. The information is always stored on your local-browser, so installing the required plugins will make your pre-existing tiddlers behave like shadow tiddlers. This means that your old tiddlers will live on the html file while the new ones will be added to the browser's storage. Not to mention that using the online version will allow you to use it without any download, installation or synchronization mechanism other than NoteSelf on it's own.

The process of installing the required plugins is not easy. This is the list of the very basic requirements:
- Tiddlypouch
- tw5-pouchdb https://github.com/danielo515/tw5-pouchdb

The second plugin only contains the required pouchdb library, which is not present on the online edition because it is downloaded from a CDN, which is much more efficient.

What plugins have you installed ?

Also, could you help why do you want this ? Which plugins do you miss/need ? What is the expected improvements over using the online version? Have you tried just dropping your old tw into the online version of NoteSelf ? Your requirement is a common one, and I don't understand why.

Regards

**Comment by mauloop** [comment]
Hi @danielo515,

thank you very much for your answer. I also read the thread #27. I experienceed the same issues mentioned there, and now it is clear for me that happened because of Tiddlyfox.

> What plugins have you installed ?

- Tiddlypouch
- manually added the `<script>` section in the `<head>` of my Tiddlywiki html file

> The information is always stored on your local-browser, so installing the required plugins will make your pre-existing tiddlers behave like shadow tiddlers. This means that your old tiddlers will live on the html file while the new ones will be added to the browser's storage. 

I did not understand this before your explanation.

> Not to mention that using the online version will allow you to use it without any download, installation or synchronization mechanism other than NoteSelf on it's own.

True, but I would prefer a local copy of the software, to have a chance to use it while offline.

> Your requirement is a common one, and I don't understand why.

I can tell my own reasons. First of all I misunderstood the behaviuor of Noteself. Now it is more clear to me, due to your kindly answer. Second I sometimes feel like a child that need his own game to open and break. Third I think that your project is very good, but I'd like to be free to apply the Tiddlywiki mainstream updates, without dependencies from a (really great) fork.

I see that there are no conflicts by now, but the option to add Noteself functionality as a plugin, would make me feel more comfortable. This is just my today opinion. Maybe tomorrow I will change my mind. I said that I'm like a child... ;^)))

**Comment by mauloop** [comment]
Just a last minute update. I tried again the steps I told in my previous post, using Chrome, hence without Tiddlyfox:

1. installed "tiddlypouch for Tiddlywiki" plugin (drag'n'drop from Noteself online)
2. manually added with a text editor all the stuff between `<!--~~ Raw markup ~~-->` mark and `</head>`

It seems to work. But I was still not satisfied, so I tried one more experiment:

1. installed "tiddlypouch for Tiddlywiki" plugin (drag'n'drop from Noteself online)
2. created a new tiddler tagged `$:/tags/RawMarkup` (I titled it "PouchDB-init", but the tiddler title doesn't really matter), with all the PouchDB related stuff from the `<head>` section.

It seems to work too.

**Comment by danielo515** [comment]
Hello again @mauloop,

Glad you're having fun with NoteSelf . Seems you are the kind of user that can take care of setting things by himself and overcome the possible issues. There is also an empty edition available for download on the Noteself site. It should work like an standalone edition with NoteSelf installed, if you want to play with it also.

> Second I sometimes feel like a child that need his own game to open and break. 

I feel the same many times. In fact that is why Noteself exists !

> True, but I would prefer a local copy of the software, to have a chance to use it while offline.

I'll reveal to you other cool thing about NoteSelf: it also saves itself on your browser. So visiting the online version even without internet connectivity should allow you to use it. Obviously you have to visit the online version at least once having internet connectivity, but after that everything should be fine no matter if you have access to Internet or not. Try it and let me know if it works for you

**Comment by mauloop** [comment]
Hi, Danielo.

I experimented with Tiddliwiki since its Classic release. One year ago I completely abandoned Evernote and moved all of my notes to Tiddlywiki. I keep my Tiddlywiki on Dropbox, and use it with my laptop, as well as with my phone or my office computer.

I'm not a novice with computers and programming, but I'm not experienced with html/css/js. That's why I love Tiddlywiki, cause it let me expand the functionality, with less knowledge.  

When I first read of Noteself I was excited about it, cause it looked like the perfect replacement for Evernote and I still think it is. I'll experiment further with Noteself, following your suggestions.

Thanks for your support.

**Comment by danielo515** [comment]
Glad you find it useful and to have someone like you around. Regards
