### ISSUE TITLE
iOS issue: Cannot open using Firefox, Chrome or Safari for iOS

### ISSUE THREAD

**Issue by dioclecio** [NoteSelf/NoteSelf.github.io#27]
Dear @danielo515 ,

I tried to use your Noteself this weekend, and I noticed some specific issues. 

When using the online version (your hosting and my personal hosting) I receive the following error using Chrome or Firefox for iOS. 

![img_0508](https://cloud.githubusercontent.com/assets/1454277/25599763/36b83488-2eb5-11e7-94ea-7e4abc6db71c.png)

When using Safari, I receive no error but a eternal looping of refreshing. 

I need to use and sync 4 devices (2 macs, 1 iPad and 1 iPhone). In my macs, I can make it work, but not in my idevices. 

If you need further information, please tell me. 

I have another question: 
I read that you propose the Noteself as a platform. Why dont you put it as just a useful plugin for the Tiddlywiki? I think it should be more easy to modify. I think. 

I read that you have plans to make it a plugin that we could install. 

![noteself_ _your_selfish_notebook](https://cloud.githubusercontent.com/assets/1454277/25599866/f9d9cc60-2eb5-11e7-8e31-b760a6fbae96.png)

Did you have some problems?

Sincerely yours. 

Dioclecio

**Comment by danielo515** [comment]
Hello @dioclecio ,
 thanks for trying NoteSelf

Could you please tell me which version of iOs are you using? I have just one Ipad and I would like to try to reproduce the issue.

Regarding your second requirement, installing this as a plugin, it is already possible, but It's my intention to make that much easier than it is now. Please take a look at my response to #26 

> Why dont you put it as just a useful plugin for the Tiddlywiki? I think it should be more easy to modify. I think.

Why do you think that? What do you want to modify? You can install any plugin on the online version, the only requirement is a browser refresh after it.

Regards

**Comment by dioclecio** [comment]
Hello Mr. Danielo,

>Regarding your second requirement, installing this as a plugin, it is already possible, but It's my intention to make that much easier than it is now. Please take a look at my response to #26

> Why do you think that? What do you want to modify? You can install any plugin on the online version, the only requirement is a browser refresh after it.

It is not my intention to criticize your Noteself. It is a very good tool. It could be more useful If it could be part of the main line of the Tiddlywiki plugins. 

Sure, I would like to contribute with the code. But, I am an average user of Tiddlywiki with very superficial Javascript knowledge. Very.

When I mentioned to change some parts, I would like to make my personal changes for my personal use, only. Something like a default setup for a specific database url in a personal hosted file. 

Another thing. In your Noteself file, you inserted some PouchDB code on the beginning (lines 54 to 60). Sometimes, repeating sometimes, if I import or insert some tiddlers and save it using Tiddlyfox, the PouchDB code suddenly disappears making the file unusable. Strange, very strange. 

I dont know if Tiddlyfox changes the main code of the Noteself. I really dont know. 

> Could you please tell me which version of iOs are you using? I have just one Ipad and I would like to try to reproduce the issue.

I use the iOS 9.3.5 in my iPad Mini 4. I tested it using Chrome, Firefox and Safari. And I always get the same Internal Javascript error. 

Again, thank you for your great tool. 

Yours, 

Dioclecio

**Comment by danielo515** [comment]
Hello @dioclecio 

> It is not my intention to criticize your Noteself. It is a very good tool. It could be more useful If it could be part of the main line of the Tiddlywiki plugins.

Don't worry, I understand. NoteSelf is an edition for two reasons. One is that I want to make it a separate product. The other one is because tiddlywiki author (Jeremy  ) is taking several decisions that are against workflows that does not fit his mind. Seems that sync-adaptors are not a priority, and NoteSelf has in her heart a syncadaptor (TiddlyPouch). There are also other issues, like Jermolene/TiddlyWiki5#2159, which prevents from correct header content injection on save. That's why you can not use tiddlyfox to save NoteSelf. I bet your problem only happens on odd or even saves, but not both. Overcoming this issue required some hacks to tiddlywiki, and therefore proper saving a NoteSelf wiki is only possible from an already NoteSelf powered wiki.
For those (and incoming) reasons, I need more fine grained control about the build process and what is included by default, and that is why it's hard to use TiddlyPouch as just a plugin.

>When I mentioned to change some parts, I would like to make my personal changes for my personal use, only. Something like a default setup for a specific database url in a personal hosted file.

I suppose do you mean to add your customizations to a NoteSelf-powered wiki, and use it as a base for other wikis, sharing the same base configuration across all the databases/notebooks. Other than that, as I said makes little sense in my mind. You can add as many customizations as you want to an specific database and it will work just fine, but constrained to that particular database. This is in my oppinion one of the strongest points of Noteself.
If what you want **is to hardcode the url of your database on the html file**, and then be able to provide just the username/password every time you visit your online wiki this is currently not possible. I have plans to include such a feature, but it is not available just now.

At the very beginning, before even NoteSelf was a TW edition, TiddlyPouch provided a way to save the current wiki configuration in an empty tiddlywiki file, providing something similar to what you are looking for. This was required because it was impossible to load plugins from the browsers database  and other deeper customizations before TW starts. After fixing that limitation I removed this feature because 1) it was hard to maintain to me and , funny thing, 2) I thought that nobody will use it. There is a remaining UI on the TiddlyPouch tab of the control pane, but it does not work.


> Another thing. In your Noteself file, you inserted some PouchDB code on the beginning (lines 54 to 60). Sometimes, repeating sometimes, if I import or insert some tiddlers and save it using Tiddlyfox, the PouchDB code suddenly disappears making the file unusable. Strange, very strange.

This happens because Jermolene/TiddlyWiki5#2159, and before I discovered it I was as confused as you.

> Sure, I would like to contribute with the code. But, I am an average user of Tiddlywiki with very superficial Javascript knowledge. Very.

Surely TiddlyPouch has a big javascript codebase. However, the UI really needs polishment, and I will love to accept any pull request for improving it. As you know, the UI is just wikitext, so feel free to give it a try. The code of TiddlyPouch is here:

https://github.com/danielo515/tiddlypouch

> I use the iOS 9.3.5 in my iPad Mini 4. I tested it using Chrome, Firefox and Safari. And I always get the same Internal Javascript error.

I have an ipad mini at home, will try.

Regards

**Comment by riddla** [comment]
Any updates on the iOS problem? I'm facing the same issue with iOS 10.2.1 on an iPhone 5.

**Comment by timborn** [comment]
Another example of infinite looping on startup using Safari 11.0 / OS X 10.12

jsconsole: 

[Error] WebSQL threw an error – SecurityError (DOM Exception 18): The operation is insecure.
SecurityError (DOM Exception 18): The operation is insecure.openDatabaseWt — NoteSelf.html:56:4244Jt — NoteSelf.html:56:4326Xt — NoteSelf.html:56:10507$t — NoteSelf.html:56:16841Te — NoteSelf.html:55:7901(anonymous function) — NoteSelf.html:136Global Code — NoteSelf.html:288
	S (NoteSelf.html:54:28426)
	(anonymous function) (NoteSelf.html:56:645)
	$t (NoteSelf.html:56:16841)
	Te (NoteSelf.html:55:7901)
	(anonymous function) (NoteSelf.html:136)
	Global Code (NoteSelf.html:288)
[Log] Something went wrong during plugin injection  – O {status: 500, name: "web_sql_went_bad", message: "unknown", …} (NoteSelf.html, line 275)
O {status: 500, name: "web_sql_went_bad", message: "unknown", error: true, reason: "The operation is insecure.", …}Oerror: truemessage: "unknown"name: "web_sql_went_bad"reason: "The operation is insecure."status: 500O Prototypeconstructor: function(e,t,n)toString()Error Prototypeconstructor: function()message: ""name: "Error"toString()Object Prototype
[Error] Something went wrong booting tiddlywiki  – TypeError: $tw.boot.boot is not a function. (In '$tw.boot.boot()', '$tw.boot.boot' is undefined) — NoteSelf.html:278
TypeError: $tw.boot.boot is not a function. (In '$tw.boot.boot()', '$tw.boot.boot' is undefined) — NoteSelf.html:278(anonymous function) — NoteSelf.html:278promiseReactionJob
	(anonymous function) (NoteSelf.html:280)
	promiseReactionJob

**Comment by danielo515** [comment]
Hello everyone.

Sorry for the lack of updates on the IOS side, but I don't have many chances to try it out.
I just tested on an Iphone 7, with IOS 11 and it works perfectly.

All my test on Iphone 5 were failing, but the Iphone 5 that I was using does not exist anymore, so I can't check if my recent changes have fixed the actual problem
