### ISSUE TITLE
One question about tiddler export and one about local vs. online Noteself

### ISSUE THREAD

**Issue by mauloop** [NoteSelf/NoteSelf.github.io#29]
Hi, Danielo.

Here I am again to ask for your help. I set up a with online Noteself my daily notes about fuel expenses. This is a good use case for me. I use to write daily on my Tiddlywiki the cost for every refueling, tipically with my phone. Monthly, using my laptop, I open the same TW annotations to calculate the total amount to send to my company.

The chance to sync the single tiddler to a remote db instead of the entire file on Dropbox is a little step for humankind, but a great one for me.

I've done everything following your reccomendation and I'm using Noteself online from your site. While experimenting I sometimes opened the same notebook with a downloaded copy of Noteself. I remember I've read somewhere that the same notebook cannot be open with both local and online Noteself, since they are registerd differently on the browser db. Do I remember right or not? In the case can you show me a way to inspect/clean my browser db? I need to avoid the case to inadvertently sync an old copy of my datas.

Another question: `export tiddler/.tid file` does not work any more. It does not export `tiddlername.tid`, but `MyNotebook.json`, which seems to contain a json with all the tiddlers from my browser db. I experienced the same issue with Firefox and Chrome, using Noteself online as well as with a downloaded copy.

Thanks in advance for your attention.

**Comment by danielo515** [comment]
Hello @mauloop , you are welcome
> I use to write daily on my Tiddlywiki the cost for every refueling, tipically with my phone.

I do exactly the same with my training sessions. Glad you decided to try NoteSelf for something like that.


> I remember I've read somewhere that the same notebook cannot be open with both local and online Noteself, since they are registerd differently on the browser db. Do I remember right or not?

Yes, that's correct. Browsers impose restrictions based on domain (ej, google.es). Each domain gets its own "piece of memory" which is private to it. Because when you open a file the domain is `file:///yourfile.html` the browser sees it as a different domain and restricts the access to it's own memory space.

> I need to avoid the case to inadvertently sync an old copy of my datas.

I don't want to make any kind of promise on this matter, but it is not likely to happen. One of the reasons to create NoteSelf and picking pouchdb as storage solution was because I lost information when importing an old tiddlywiki into my working tiddlywiki. Tiddlywiki does not care about properly mergin files, and it's very easy to override a tiddler with it's old version. This does not happen with Pouchdb because each tiddler gets an UUID and a revision hash. The revision hash indicates how old and which revision a tiddler is at. Using that information Pouchdb will not allow you to override a tiddler with an old version of itself.

In any case, if you want to examine the data on your databases, and make sure how things are going I recommend you to install the following chorme extension:

https://chrome.google.com/webstore/detail/pouchdb-inspector/hbhhpaojmpfimakffndmpmpndcmonkfa

You just have to click on the button I have highlighted on the below screenshot 

![image](https://cloud.githubusercontent.com/assets/2270425/26032970/d24fc20e-38a0-11e7-9c39-cb9485272c36.png)

Then an icon will appear on your browsers navigation bar.
Then navigate to the online version of NoteSelf or open your local file. Open the developers tools (hit F12 on windows) and you should have a Pouchdb tab on it, like the image below:

![image](https://cloud.githubusercontent.com/assets/2270425/26033008/afbb5158-38a1-11e7-8fbe-0eb4766a49b2.png)

It allows you to navigate through the databases that SPECIFIC DOMAIN HAS. Play with it and ask any doubt you get.

>Another question: export tiddler/.tid file does not work any more. It does not export tiddlername.tid, but MyNotebook.json, which seems to contain a json with all the tiddlers from my browser db.

Yes, that is a known BUG. It was introduced when someone wanted a way to backup their database. I made a fast and dirty prototype that hooks into the save mechanism, and inadvertently I broke every export mechanism. I want to fix it as soon as I could.

Regards

**Comment by mauloop** [comment]
I forget to thank you for your suggestion. PouchDB inspector is a useful tool. I added it to my Chrome apps.
In the meantime I moved two of my most frequently used TWs on Noteself.

Everything works fine. Noteself is great.

**Comment by danielo515** [comment]
Love to hear that ! Seems like NoteSelf is gaining traction
