### ISSUE TITLE
Sync OK on crazy couchdb URL

### ISSUE THREAD

**Issue by guiguid** [NoteSelf/NoteSelf.github.io#33]
Hi, 
first thanks for this amazing TW5 feature.

With online version : 
CouchDB URL : "toto"   <- yes, no http, no dots, false host....
-> Offline to online : 
```
===SYNC ACTIVE===
replicate resumed
===SYNC Change==={
    "direction": "push",
    "change": {
        "ok": true,
        "start_time": "2017-05-18T14:12:40.003Z",
        "docs_read": 1,
        "docs_written": 1,
        "doc_write_failures": 0,
        "errors": [],
        "last_seq": 49
    }
}
===SYNC PAUSED===
===SYNC ACTIVE===
replicate resumed
===SYNC Change==={
    "direction": "push",
    "change": {
        "ok": true,
        "start_time": "2017-05-18T14:12:40.003Z",
        "docs_read": 2,
        "docs_written": 2,
        "doc_write_failures": 0,
        "errors": [],
        "last_seq": 50
    }
}
===SYNC PAUSED===
===SYNC ACTIVE===
replicate resumed
===SYNC Change==={
    "direction": "push",
    "change": {
        "ok": true,
        "start_time": "2017-05-18T14:12:40.003Z",
        "docs_read": 3,
        "docs_written": 3,
        "doc_write_failures": 0,
        "errors": [],
        "last_seq": 51
    }
}
===SYNC PAUSED===
```

It's impossible, I have no host 'toto' !!!

**Comment by danielo515** [comment]
Could you please enclose the logs between three ticks? ` ``` ` like you do with tiddlywiki

**Comment by guiguid** [comment]
I have updated the issue.

(sorry for the good host issue, I haven't enabled "all domain from CROS..."
  
>CROS 
> Origin Domains
>
>Databases will accept requests from these domains:
>All domains ( * )

So the issue is : without `http` or `https`, 
After clicking on the `Offline` button, the UI show that you are online and synchronized, the log seems to show that.
But you are not ( see my silly config above with host 'toto' )

**Comment by danielo515** [comment]
Hello @guiguid

I was about to point you to the CORS configuration tutorial . Luckily you figured out yourself. Probably we can work to give a better error message and even point to the solution.

Regarding the other topic (the funny remote url ) you have discovered an undocumented (and unexpected) feature. We just provide the url to PouchDB (the internal database ) as it is. If PouchDB identifies it as a remote database (probably anything starting with http or https) then it tries to synchronize to the remote server. If it is not a remote database then it creates a new local database and synchronizes to it, that's why you see it on the log. This is something useful for several scenarios. If you check your local databases you should have one called Toto.

Regards

**Comment by danielo515** [comment]
@guiguid are you happy with the provided explanation? May we close the issue?
